language: node_js
node_js:
  - 0.10
  - 0.9
  - 0.8
  - 0.7
  - 0.6

script: "npm test"

notifications:
  email:
    recipients:
      - urodoz@gmail.com
    on_success: always
    on_failure: always
